[package]
name = "busd"
description = "Generic local message bus and IPC broker."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["unix"]
unix = ["dep:bus-transport-unix"]
dbus = []
monitoring = []

[dependencies]
bus-broker = { path = "../bus-broker" }
bus-client = { path = "../bus-client" }
bus-policy = { path = "../bus-policy" }
bus-protocol = { path = "../bus-protocol" }
bus-transport-unix = { path = "../bus-transport-unix", optional = true }

[dev-dependencies]
bus-client = { path = "../bus-client" }

[lints]
workspace = true
