[package]
name = "bus-client"
description = "Application-facing client library for BUS/1."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
bus-protocol = { path = "../bus-protocol" }
bus-transport-unix = { path = "../bus-transport-unix" }

[lints]
workspace = true
